name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: pharmacy-chatbot-backend
          publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
          package: ./backend
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: pharmacy-chatbot-frontend
          publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
          package: ./frontend
    
